### ISSUE TITLE
window.crypto.randomuuid is not a function

### ISSUE THREAD

**Issue by DesignHhuang** [luizzappa/vue-circle-flags#1]
There is a warning about `window.crypto.randomuuid is not a function` when i use this component with vue3 & vite.

**Comment by luizzappa** [comment]
Hi @DesignHhuang, this error was not supposed to occur because the generation of the random uuid is within `onMounted`, which is only called in the browser. Anyway, I published a new version simplifying it so that the uuid is hard coded and no longer needs this function at run time. 

Please update to version 1.0.9 and this error should disappear:

```
npm install vue-circles-flags@1.0.9
```

I will close this issue, if the error persists feel free to reopen it.

**Comment by luizzappa** [comment]
[d941d10](https://github.com/luizzappa/vue-circle-flags/commit/d941d1028f8d6d01c2cacfa5c95d9f9c1e52a017)
